sudo: required
dist: trusty
language: node_js
node_js:
  - "0.11"
  - "0.10"
env:
  - CXX=g++-4.8
  - TEST_DIR=client_viten
  - TEST_DIR=server
addons:
apt:
  sources:
    - google-chrome
    - ubuntu-toolchain-r-test
  packages:
    - google-chrome-stable
    - google-chrome-beta
    - g++-4.8
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

before_script:
- npm install -g angular-cli@1.0.0-beta.26
- npm install

script: cd $TEST_DIR && npm install && npm run buildtest
